### ISSUE TITLE
Allow localhost to be added to the URL list

### ISSUE THREAD

**Issue by gregorwinkler** [8hobbies/plausible-shield#54]
Your browser extension is working great and helps us to effectively filter out our own usage of our apps and websites.

However, localhost cannot be added to the URL list of the extension, it results in the following error:
_"http://localhost" is not a valid URL prefix. A valid URL prefix must be a valid URL itself._

The localhost can be as well filtered out in the Plausible dashboard, but it would be nice to have it blocked with your extension as well, so that data coming from localhost in not even tracked and the pageviews contingent not used for it.

You may want to consider as well the usage of ports in conjunction with localhost (e.g. localhost:3333).

**Comment by xuhdev** [comment]
Is your plausible tracking localhost? The [Plausible doc](https://plausible.io/docs/troubleshoot-integration#are-you-running-on-localhost) says:

> Our script automatically disables itself when running on localhost as most people don't want those stats to be counted. In the script.js script, window.location.hostname is used to verify that. If you do want to track stats on localhost, you can [use our extension](https://plausible.io/docs/script-extensions).

**Comment by gregorwinkler** [comment]
Oh you're right, I just forgot about that part as I had localhost activated in the script for testing purposes.

Then this is actually not a real issue anymore. May still be nice as an improvement, but not necessary by any means.

Thanks for your quick response!

**Comment by xuhdev** [comment]
Perfect! Glad it works!

Probably not gonna implement it unless someone reports a valid use case. Since Plausible disables localhost by default, allowing localhost specified in the plugin may lead to confusing behaviors.
